source 'https://rubygems.org'
gem "ffi", "< 1.17.0"
gem "webrick"
gem "github-pages"
gem "jekyll-coffeescript"
gem "jekyll-default-layout"
gem "jekyll-gist"
gem "jekyll-github-metadata"
gem "jekyll-optional-front-matter"
gem "jekyll-paginate"
gem "jekyll-readme-index"
gem "jekyll-titles-from-headings"
gem "jekyll-relative-links"
